# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "34643a36e680b5ac9c6075c5d793596f"
name = "sr-tickets-sync-app"
application_url = "https://example.com"
embedded = false

[access_scopes]
scopes = "read_orders"

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  uri = "/api/shopify/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/api/shopify/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/api/shopify/webhooks/orders"
  topics = [ "orders/create", "orders/updated" ]

[auth]
redirect_urls = [
  "https://example.com/api/shopify/auth/callback",
]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false
